# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Aug 14 22:17:33 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(538, 531)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.winSize = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winSize.sizePolicy().hasHeightForWidth())
        self.winSize.setSizePolicy(sizePolicy)
        self.winSize.setObjectName(_fromUtf8("winSize"))
        self.gridLayout.addWidget(self.winSize, 1, 1, 1, 1)
        self.winXPos = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winXPos.sizePolicy().hasHeightForWidth())
        self.winXPos.setSizePolicy(sizePolicy)
        self.winXPos.setObjectName(_fromUtf8("winXPos"))
        self.gridLayout.addWidget(self.winXPos, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.winYPos = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winYPos.sizePolicy().hasHeightForWidth())
        self.winYPos.setSizePolicy(sizePolicy)
        self.winYPos.setObjectName(_fromUtf8("winYPos"))
        self.gridLayout.addWidget(self.winYPos, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.winFullscreen = QtGui.QCheckBox(self.groupBox)
        self.winFullscreen.setObjectName(_fromUtf8("winFullscreen"))
        self.gridLayout.addWidget(self.winFullscreen, 0, 0, 1, 1)
        self.winScreenID = QtGui.QSpinBox(self.groupBox)
        self.winScreenID.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winScreenID.sizePolicy().hasHeightForWidth())
        self.winScreenID.setSizePolicy(sizePolicy)
        self.winScreenID.setObjectName(_fromUtf8("winScreenID"))
        self.gridLayout.addWidget(self.winScreenID, 0, 1, 1, 1)
        self.winXOffset = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winXOffset.sizePolicy().hasHeightForWidth())
        self.winXOffset.setSizePolicy(sizePolicy)
        self.winXOffset.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.winXOffset.setAccelerated(False)
        self.winXOffset.setMinimum(-10000)
        self.winXOffset.setMaximum(10000)
        self.winXOffset.setObjectName(_fromUtf8("winXOffset"))
        self.gridLayout.addWidget(self.winXOffset, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.winYOffset = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winYOffset.sizePolicy().hasHeightForWidth())
        self.winYOffset.setSizePolicy(sizePolicy)
        self.winYOffset.setAccelerated(False)
        self.winYOffset.setMinimum(-10000)
        self.winYOffset.setMaximum(10000)
        self.winYOffset.setObjectName(_fromUtf8("winYOffset"))
        self.gridLayout.addWidget(self.winYOffset, 6, 1, 1, 1)
        self.winScale = QtGui.QDoubleSpinBox(self.groupBox)
        self.winScale.setDecimals(1)
        self.winScale.setSingleStep(0.1)
        self.winScale.setObjectName(_fromUtf8("winScale"))
        self.gridLayout.addWidget(self.winScale, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bgrLines = QtGui.QLineEdit(self.groupBox_2)
        self.bgrLines.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgrLines.sizePolicy().hasHeightForWidth())
        self.bgrLines.setSizePolicy(sizePolicy)
        self.bgrLines.setObjectName(_fromUtf8("bgrLines"))
        self.gridLayout_2.addWidget(self.bgrLines, 1, 1, 1, 1)
        self.bgrEnable = QtGui.QCheckBox(self.groupBox_2)
        self.bgrEnable.setObjectName(_fromUtf8("bgrEnable"))
        self.gridLayout_2.addWidget(self.bgrEnable, 0, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.bgrCoverage = QtGui.QLineEdit(self.groupBox_2)
        self.bgrCoverage.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgrCoverage.sizePolicy().hasHeightForWidth())
        self.bgrCoverage.setSizePolicy(sizePolicy)
        self.bgrCoverage.setObjectName(_fromUtf8("bgrCoverage"))
        self.gridLayout_2.addWidget(self.bgrCoverage, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.imP2 = QtGui.QLineEdit(self.groupBox_4)
        self.imP2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imP2.sizePolicy().hasHeightForWidth())
        self.imP2.setSizePolicy(sizePolicy)
        self.imP2.setObjectName(_fromUtf8("imP2"))
        self.gridLayout_3.addWidget(self.imP2, 2, 1, 1, 1)
        self.imP1 = QtGui.QLineEdit(self.groupBox_4)
        self.imP1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imP1.sizePolicy().hasHeightForWidth())
        self.imP1.setSizePolicy(sizePolicy)
        self.imP1.setObjectName(_fromUtf8("imP1"))
        self.gridLayout_3.addWidget(self.imP1, 1, 1, 1, 1)
        self.imEnable = QtGui.QCheckBox(self.groupBox_4)
        self.imEnable.setTristate(False)
        self.imEnable.setObjectName(_fromUtf8("imEnable"))
        self.gridLayout_3.addWidget(self.imEnable, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.imMin = QtGui.QLineEdit(self.groupBox_4)
        self.imMin.setEnabled(False)
        self.imMin.setObjectName(_fromUtf8("imMin"))
        self.gridLayout_3.addWidget(self.imMin, 3, 1, 1, 1)
        self.imMax = QtGui.QLineEdit(self.groupBox_4)
        self.imMax.setEnabled(False)
        self.imMax.setObjectName(_fromUtf8("imMax"))
        self.gridLayout_3.addWidget(self.imMax, 4, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabLG = QtGui.QTableWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLG.sizePolicy().hasHeightForWidth())
        self.tabLG.setSizePolicy(sizePolicy)
        self.tabLG.setRowCount(6)
        self.tabLG.setColumnCount(6)
        self.tabLG.setObjectName(_fromUtf8("tabLG"))
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabLG.setHorizontalHeaderItem(5, item)
        self.tabLG.horizontalHeader().setCascadingSectionResizes(False)
        self.tabLG.horizontalHeader().setDefaultSectionSize(40)
        self.tabLG.horizontalHeader().setHighlightSections(True)
        self.tabLG.horizontalHeader().setMinimumSectionSize(30)
        self.horizontalLayout_4.addWidget(self.tabLG)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.hgIntensity = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.hgIntensity.setMaximum(1.0)
        self.hgIntensity.setSingleStep(0.1)
        self.hgIntensity.setProperty("value", 0.0)
        self.hgIntensity.setObjectName(_fromUtf8("hgIntensity"))
        self.gridLayout_4.addWidget(self.hgIntensity, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.hgTwist = QtGui.QSpinBox(self.groupBox_5)
        self.hgTwist.setObjectName(_fromUtf8("hgTwist"))
        self.gridLayout_4.addWidget(self.hgTwist, 1, 1, 1, 1)
        self.hgZ = QtGui.QSpinBox(self.groupBox_5)
        self.hgZ.setObjectName(_fromUtf8("hgZ"))
        self.gridLayout_4.addWidget(self.hgZ, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setStatusTip(_fromUtf8(""))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.label_2.setBuddy(self.winXPos)
        self.label_3.setBuddy(self.winYPos)
        self.label.setBuddy(self.winSize)
        self.label_9.setBuddy(self.winXOffset)
        self.label_10.setBuddy(self.winYOffset)
        self.label_6.setBuddy(self.bgrCoverage)
        self.label_5.setBuddy(self.bgrLines)
        self.label_8.setBuddy(self.imP2)
        self.label_7.setBuddy(self.imP1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.winFullscreen, self.winScreenID)
        MainWindow.setTabOrder(self.winScreenID, self.winSize)
        MainWindow.setTabOrder(self.winSize, self.winXPos)
        MainWindow.setTabOrder(self.winXPos, self.winYPos)
        MainWindow.setTabOrder(self.winYPos, self.winXOffset)
        MainWindow.setTabOrder(self.winXOffset, self.winYOffset)
        MainWindow.setTabOrder(self.winYOffset, self.bgrEnable)
        MainWindow.setTabOrder(self.bgrEnable, self.bgrLines)
        MainWindow.setTabOrder(self.bgrLines, self.bgrCoverage)
        MainWindow.setTabOrder(self.bgrCoverage, self.imEnable)
        MainWindow.setTabOrder(self.imEnable, self.imP1)
        MainWindow.setTabOrder(self.imP1, self.imP2)
        MainWindow.setTabOrder(self.imP2, self.tabLG)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QtSLM", None))
        self.groupBox.setTitle(_translate("MainWindow", "Window", None))
        self.winSize.setText(_translate("MainWindow", "768", None))
        self.winXPos.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "X Position", None))
        self.winYPos.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Y Position", None))
        self.label.setText(_translate("MainWindow", "Size", None))
        self.label_4.setText(_translate("MainWindow", "Waist Scale", None))
        self.winFullscreen.setText(_translate("MainWindow", "Fullscreen", None))
        self.label_9.setText(_translate("MainWindow", "X Offset", None))
        self.label_10.setText(_translate("MainWindow", "Y Offset", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Blazed Grating", None))
        self.bgrLines.setText(_translate("MainWindow", "180", None))
        self.bgrEnable.setText(_translate("MainWindow", "Enable", None))
        self.label_6.setText(_translate("MainWindow", "Coverage", None))
        self.label_5.setText(_translate("MainWindow", "Lines", None))
        self.bgrCoverage.setText(_translate("MainWindow", "0.9", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Intensity Map", None))
        self.label_8.setText(_translate("MainWindow", "P2 [0..1]", None))
        self.label_7.setText(_translate("MainWindow", "P1 [0..1]", None))
        self.imP2.setText(_translate("MainWindow", "0.35", None))
        self.imP1.setText(_translate("MainWindow", "0.005", None))
        self.imEnable.setText(_translate("MainWindow", "Enable", None))
        self.label_14.setText(_translate("MainWindow", "min", None))
        self.label_15.setText(_translate("MainWindow", "max", None))
        self.imMin.setText(_translate("MainWindow", "0", None))
        self.imMax.setText(_translate("MainWindow", "255", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "LG Modes", None))
        item = self.tabLG.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tabLG.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tabLG.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tabLG.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tabLG.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tabLG.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tabLG.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tabLG.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tabLG.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tabLG.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tabLG.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tabLG.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "5", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "HG Modes", None))
        self.label_13.setText(_translate("MainWindow", "Intensity", None))
        self.label_11.setText(_translate("MainWindow", "z", None))
        self.label_12.setText(_translate("MainWindow", "Twist", None))

